### ISSUE TITLE
Poster fails to compile on windows 8.1 and windows 10

### ISSUE THREAD

**Issue by anupamsingh81** [brentthorne/posterdown#12]
windows 10.1 (R 3.3.3 ) 
error..

tlmgr search --file --global "/biblatex-dm.cfg"
tlmgr search --file --global "/win.bbl"  #(win is name of poster)
! Package longtable Error: longtable not in 1-column mode.

pastebin of log here..https://pastebin.com/g5ju7pS4

windows 8.1(R 3.5)
biblatex-dm.cfg not found
/poster..bbl not found

**Comment by anupamsingh81** [comment]
Both windows versions have a fresh install of texlive via tinytex

**Comment by brentthorne** [comment]
Looking at your tex output file it show this on lines 1810 and 1811:
```
Package biblatex Info: ... file 'win.bbl' not found.
No file win.bbl.
```
Did you change the name of the `.bib` file in the YAML? 

Also could you post your Rmd file like you did with the log output so I can see if the issue lies there?

There may be conflicts with naming the .Rmd file the same as the .bib file.

**Comment by anupamsingh81** [comment]
Reinstalled tinytex , updated R to 3.5.2 on windows 10..n issue vanishes....poster compiled successfully..

Sorry for bothering..will try on windows 8.1 tomorrow n then revert.

**Comment by brentthorne** [comment]
Okay thanks, I will close the issue for now but will consider looking into investigating the backwards compatibility of posterdown in the future. I haven't had it tested on Windows 8 with updated specs so if it works feel free to let me know!

Thanks
