### ISSUE TITLE
adding subtitle?

### ISSUE THREAD

**Issue by SwampThingPaul** [brentthorne/posterdown#71]
1st awesome template and package!!
I am trying to have variable font in the title, essentially making a title (bigger font) with a subtitle (slightly smaller font). 

I started by making a "subtitle" object then adding it to the <h1></h1> tag in a custom CSS file. Below is what I tried to do but keep running in circles. Am I going about it in the right way? 

```{css, echo=F}
#title {
font-size: $title_textsize$;
text-align: left;
padding-right: 7%;
padding-left: 7%;
margin: 0;
line-height: 90%;
border-bottom: 0;
}

#subtitle {
font-size: calc($title_textsize$/2);
text-align: left;
padding-right: 7%;
padding-left: 7%;
margin: 0;
line-height: 90%;
border-bottom: 0;
}

<div class="poster_wrap">
<div class="column outer">
<br>
<h1 id="title">$title$</h1>
<h1 id="subtitle">$subtitle$</h1>
<br>
</div>
</div>
```

**Comment by SwampThingPaul** [comment]
I also did a hacky way of using HTML to alter the title so that it looks something like this in the yaml

```
title: Title<br><text size="75">subtitle</font>
```

**Comment by brentthorne** [comment]
Hello and thanks for trying out posterdown! Can I ask which template you are using?

The only thing I might change for the subtitle option if using an `$if()$` pandoc statement so that the user can choose to not have one if they don't include it in the YAML, otherwise the document would not knit due to a missing field. For your purposes though you've done the right work!

Here's what I will use when I get to it:
```html
<h1 id="title">$title$</h1>
$if(subtitle)$<h1 id="subtitle">$subtitle$</h1>$endif$
<h3 id="author">$author$</h3>
```

I am currently working on majour overhauls of the YAML functionality to both simplify and clean up inconsistencies. I will certainly include a subtitle section. 

Cheers

**Comment by SwampThingPaul** [comment]
Hi @brentthorne I am using the "posterdown_betterland" template. I'll try the suggestion above. Thanks for the help.
