### ISSUE TITLE
reference list/citations do not appear at end of document

### ISSUE THREAD

**Issue by eebrown** [brentthorne/posterdown#73]
With a new installation using the default Latex Rmd template, the reference list does not appear (nor does the final "References" header).

**Comment by eebrown** [comment]
And I believe it can be fixed by adding `\printbibliography` to line 241 of template.tex

**Comment by brentthorne** [comment]
Yes that was mistakenly removed, thanks for notifying me I will add it to the template soon.

Cheers!

**Comment by seb951** [comment]
Can you add it to the posterdown_pdf/skeleton/skeleton.Rmd file too? 

thanks

**Comment by brentthorne** [comment]
Hi @seb951 ,

`posterdown_pdf` has been depreciated and is only kept in for legacy users (if that's even a thing I don't know, but it's here just in case)

This means there will be no changes to the `posterdown_pdf` temeplate, however, the `posterdown_latex` option was created from the `posterdown_pdf` one and was only changed to differentiate it from the `posterdown_html` option. Both the `posterdown_latex` and `posterdown_html` options produce PDF outputs which is why I changed the naming of them. 

As a quick fix if you don't wish to use the `posterdown_latex` option is to simply add the `\printbibliography` line into your own Rmd file which will work jsut the same even though it's LaTeX it will still work fine thanks to the magic of RMarkdown!
