### ISSUE TITLE
nopagecolor

### ISSUE THREAD

**Issue by seb951** [brentthorne/posterdown#75]
I keep getting this warning message when knitting the posterdown_pdf/skeleton/skeleton.Rmd file? It does not seem to affect the output, but not sure how to fix it?! 

thanks. Great package by the way.

Warning message:
Package pagecolor Warning: \nopagecolor does not work with
(pagecolor)                the used crop package. Using
(pagecolor)                none
(pagecolor)                as nopagecolor now
(pagecolor)                 on input line 231.
Package pagecolor Warning: Option nopagecolor=none requested 
(pagecolor)                but this does not work with the crop package.
(pagecolor)                By option nopagecolor the "colour" to be used with \
nopagecolor
(pagecolor)                is set. The current value is "none" (maybe by defaul
t),
(pagecolor)                but the crop package broke \nopagecolor.
(pagecolor)                Therefore the colour cannot be "none".
(pagecolor)                Please change the option accordingly!
(pagecolor)                As first aid nopagecolor is now set to white
(pagecolor)                 on input line 231.

**Comment by brentthorne** [comment]
Hello @seb951, thanks for trying posterdown!

posterdown_pdf has been dropped and is only still available as a legacy option. I would strongly recommend using posterdown_latex to produce a pdf poster from a LaTeX document. I would also suggest using the posterdown_html option which also produces a pdf but will have much more support from me personally as I have a much better background/ understanding of HTML/CSS as compared o LaTeX.

If you get the same error in posterdown_latex please let me know here! Since it isn't influencing the final output of the poster it probably won't be a priority for me to look into now.

Cheers
