### ISSUE TITLE
 Failed to find a package that contains biblatex-dm.cfg

### ISSUE THREAD

**Issue by goodlebang** [brentthorne/posterdown#76]
Hi bretthorne
Thank you for your wonderful package.
By using it, I tried to make a poster for academic meeting.
When I tried to make tables with kable() function, can`t knitting and showed me an error message How can I do it for?

**Comment by brentthorne** [comment]
Hello,

Can you provide the code used to make the kable table, often the problem is that the the {knitr} package is not loaded in the R chunk. Without knowing what your code looks like my only guess would be that you should make sure to use 

```r
knitr::kable()
```
rather than just 

```r
kable()
```

Thanks for using {posterdown} and please post your code for the error (hopefully a reproducible example) and I will do my best to help debug.

Cheers!

**Comment by goodlebang** [comment]
Great thanks! 
It works well!

**Comment by brentthorne** [comment]
Happy to help!

**Comment by goodlebang** [comment]
Hello
I have one more question.
If I try to make a markdown table, it can not work!,
