### ISSUE TITLE
R version 3.6.1 install failure pagedown non-zero exit status

### ISSUE THREAD

**Issue by cbaileyphd** [brentthorne/posterdown#92]
I updated my version of R (to 3.6.1) and when reinstalling packages, I can't get posterdown to install. I get the same message in vanilla R and in Rstudio 

ERROR: dependency ‘websocket’ is not available for package ‘pagedown’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pagedown’
Error: Failed to install 'posterdown' from GitHub:
  (converted from warning) installation of package ‘pagedown’ had non-zero exit status

**Comment by brentthorne** [comment]
Hello!

Looks like you need to have websocket installed. Any chance you could provide info on what operating system you are running.

Also if it is an issue larger than just the websocket install it will be with [`pagedown` ](https://github.com/RStudio/pagedown) rather than `posterdown` which is built off of it.

**Comment by cbaileyphd** [comment]
Thanks for the quick reply.  I am running macOS Mojave 10.14.5
I tried installing websocket and pagedown, but both have non-zero exit status and the install fails. Here's the error message from pagedown.
  
 `1 error generated.
 make: *** [RcppExports.o] Error 1
 ERROR: compilation failed for package ‘websocket’
 * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/websocket’
 Warning in install.packages :
   installation of package ‘websocket’ had non-zero exit status
 ERROR: dependency ‘websocket’ is not available for package ‘pagedown’
 * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pagedown’
 Warning in install.packages :
   installation of package ‘pagedown’ had non-zero exit status
`

**Comment by remlapmot** [comment]
Do you have mac OS Command line tools installed?

I think that you need these installed because websocket is only available as a source package for r-release for mac OS from CRAN:
<https://cran.r-project.org/web/packages/websocket/index.html>

On mac OS to install command line tools (without installing all of Xcode, which is a large download) in a Terminal session I think you can run:
```
xcode-select --install
```
After you have installed these restart RStudio (or however you're running R).

**Comment by cbaileyphd** [comment]
That worked! Thank you

**Comment by brentthorne** [comment]
Great thanks @remlapmot !
