### ISSUE TITLE
Twitter after email

### ISSUE THREAD

**Issue by TiagoVentura** [brentthorne/posterdown#96]
Hi! 

Thanks for the package. Is there a way I can move the twitter name to appear after my email address?

Thanks!

**Comment by brentthorne** [comment]
This would need to be done either in the browser afterwords which isn't ideal because you would need to do it every time you knit the document OR you would need to fork this package and change the template.html for the poster option you want. If you do fork the package and are not sure how to edit templates with html and pandoc then just make sure to allow for pull requests and I can make that change for you.
